import { useEffect, useState } from "react";
import { BookOpen, Building2, ChevronRight, LogOut } from "lucide-react";
import AndroidWorkspace from "@/components/AndroidWorkspace";\nimport { supabase } from "@/lib/supabase";

/** Accueil structurel : accès direct au bâtiment et à son catalogue de charges. */
export default function AndroidHome() {
  const [screen, setScreen] = useState<"home" | "Bâtiments" | "Catalogue des charges">("home");\n  const [email, setEmail] = useState("");\n  useEffect(() => { supabase.auth.getUser().then(({ data }) => setEmail(data.user?.email ?? "")); }, []);
  if (screen !== "home") return <AndroidWorkspace screen={screen} onBack={() => setScreen("home")} onNavigate={next => setScreen(next as typeof screen)} />;
  return <div className="android-shell fixed inset-0 z-40 overflow-y-auto bg-[#f7f7f7]">
    <header className="sticky top-0 z-10 flex h-[62px] items-center justify-between border-b border-[#ececec] bg-white px-4"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#079ca0] text-white"><Building2 className="h-4 w-4" /></div><span className="text-[15px] font-bold">GcBtp · Structure</span></div><button type="button" title={email ? `Déconnexion · ${email}` : "Déconnexion"} onClick={() => supabase.auth.signOut()} className="grid h-9 w-9 place-items-center rounded-xl border border-[#e3e9ed] bg-white text-[#71808a] hover:bg-[#f4f7f8]"><LogOut className="h-4 w-4" /></button></header>
    <main className="px-4 pb-10 pt-5"><div className="mb-5"><div className="text-[11px] font-bold uppercase tracking-wide text-[#079ca0]">Bureau d’études digital</div><h1 className="mt-1 text-[24px] font-bold text-[#102f45]">Préparer votre projet</h1><p className="mt-2 text-[12px] leading-5 text-[#78888d]">Modélisez le bâtiment et utilisez une base de charges cohérente pour vos calculs.</p></div><div className="grid gap-3 sm:grid-cols-2"><button onClick={() => setScreen("Bâtiments")} className="rounded-2xl bg-[#102f45] p-5 text-left text-white shadow-[0_10px_25px_rgba(16,47,69,.14)] transition hover:-translate-y-0.5"><div className="mb-6 grid h-11 w-11 place-items-center rounded-xl bg-white/10"><Building2 className="h-6 w-6 text-[#8dd6d4]" /></div><div className="flex items-center justify-between"><div><div className="text-[16px] font-bold">Bâtiment</div><div className="mt-1 text-[11px] text-white/65">Créer les niveaux et placer les éléments</div></div><ChevronRight className="h-5 w-5 text-[#f0b35b]" /></div></button><button onClick={() => setScreen("Catalogue des charges")} className="rounded-2xl border border-[#dce8ea] bg-white p-5 text-left shadow-[0_6px_18px_rgba(16,47,69,.05)] transition hover:-translate-y-0.5"><div className="mb-6 grid h-11 w-11 place-items-center rounded-xl bg-[#eaf4f5] text-[#079ca0]"><BookOpen className="h-6 w-6" /></div><div className="flex items-center justify-between"><div><div className="text-[16px] font-bold text-[#102f45]">Catalogue des charges</div><div className="mt-1 text-[11px] text-[#78888d]">Matériaux, poids propres, Gk et Qk</div></div><ChevronRight className="h-5 w-5 text-[#079ca0]" /></div></button></div><div className="mt-5 rounded-xl bg-[#eaf4f5] p-4 text-[11px] leading-5 text-[#436b70]"><b>Référence active :</b> béton armé C25/30, poids volumique 25 kN/m³, aciers HA400 ou HA500. Les valeurs sont modifiables ou à confirmer selon le projet.</div></main>
  </div>;
}
