import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FLOOR_PRESETS, type FloorConfig } from "@shared/floor-config";
import { validateFloorConfig } from "@shared/floor-validation";

type Props = { value: FloorConfig; onChange: (value: FloorConfig) => void; onClose: () => void };

export default function FloorConfigPanel({ value, onChange, onClose }: Props) {
  const update = (patch: Partial<FloorConfig>) => onChange({ ...value, ...patch });
  const customThickness = !FLOOR_PRESETS[value.type].includes(value.thickness);
  const errors = validateFloorConfig(value);
  const setType = (type: FloorConfig["type"]) => update(type === "Dalle pleine" ? { type, thickness: "20 cm", characteristicPermanentLoad: "8.00", characteristicImposedLoad: "1.50" } : { type, thickness: "16+4 cm", hollowBlockHeight: "16", compressionSlab: "4", characteristicPermanentLoad: "5.84", characteristicImposedLoad: "1.50" });
  return <div className="space-y-3">
    <Card><CardContent className="space-y-3 p-3">
      <div><Label>Type de plancher</Label><select className="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-[11px]" value={value.type} onChange={event => setType(event.target.value as FloorConfig["type"])}><option>Corps creux</option><option>Dalle pleine</option></select></div>
      <div><Label>Épaisseur / composition</Label><select className="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-[11px]" value={customThickness ? "__custom__" : value.thickness} onChange={event => update({ thickness: event.target.value === "__custom__" ? "" : event.target.value })}>{FLOOR_PRESETS[value.type].map(option => <option key={option}>{option}</option>)}<option value="__custom__">Épaisseur personnalisée</option></select></div>
      {customThickness && <Input value={value.thickness} placeholder={value.type === "Corps creux" ? "Ex : 20+5 cm" : "Ex : 22 cm"} onChange={event => update({ thickness: event.target.value })} />}
      <div className="grid grid-cols-2 gap-2"><div><Label>Portée indicative (m)</Label><Input inputMode="decimal" value={value.span} onChange={event => update({ span: event.target.value })} /></div><div><Label>Sens de portée</Label><select className="h-10 w-full rounded-lg border bg-white px-2 text-[11px]" value={value.direction} onChange={event => update({ direction: event.target.value as "X" | "Y" })}><option value="X">Suivant X</option><option value="Y">Suivant Y</option></select></div></div>
      {value.type === "Corps creux" ? <div className="grid grid-cols-3 gap-2"><div><Label>Entrevous (cm)</Label><Input value={value.hollowBlockHeight} onChange={event => update({ hollowBlockHeight: event.target.value })} /></div><div><Label>Dalle comp. (cm)</Label><Input value={value.compressionSlab} onChange={event => update({ compressionSlab: event.target.value })} /></div><div><Label>Nervure (cm)</Label><Input value={value.ribWidth} onChange={event => update({ ribWidth: event.target.value })} /></div></div> : <div className="rounded-lg bg-[#e7f7f6] p-3 text-[10px] text-[#166b6b]">Dalle pleine : l’épaisseur saisie représente l’épaisseur totale de la dalle en béton armé.</div>}
      <div className="rounded-lg border border-[#cfe3f5] bg-[#eef7ff] p-3"><div className="mb-2 text-[10px] font-bold uppercase tracking-wide text-[#155a9c]">Charges caractéristiques du plancher · modèle DSRCAD</div><div className="grid grid-cols-2 gap-2"><div><Label>G permanente (kN/m²)</Label><Input inputMode="decimal" value={value.characteristicPermanentLoad ?? "5.84"} onChange={event => update({ characteristicPermanentLoad: event.target.value })} /></div><div><Label>Q exploitation (kN/m²)</Label><Input inputMode="decimal" value={value.characteristicImposedLoad ?? "1.50"} onChange={event => update({ characteristicImposedLoad: event.target.value })} /></div></div><p className="mt-2 text-[9px] text-[#476276]">Valeurs caractéristiques non pondérées. Pour 16 m² : G = 93,4 kN et Q = 24,0 kN.</p></div>
      <div><Label>Classe de béton</Label><select className="h-10 w-full rounded-lg border bg-white px-2 text-[11px]" value={value.concreteClass} onChange={event => update({ concreteClass: event.target.value })}><option>C25/30</option><option>C30/37</option><option>C35/45</option></select></div><div className="rounded-lg border border-[#dfe8e8] bg-[#f8fbfb] p-3"><div className="mb-2 text-[10px] font-bold uppercase tracking-wide text-[#087f7f]">Catalogue des charges · kN/m²</div><div className="grid grid-cols-2 gap-2"><div><Label>Revêtements + chape</Label><Input inputMode="decimal" value={value.finishLoad ?? "1.00"} onChange={event => update({ finishLoad: event.target.value })} /></div><div><Label>Plafonds + réseaux</Label><Input inputMode="decimal" value={value.ceilingLoad ?? "0.30"} onChange={event => update({ ceilingLoad: event.target.value })} /></div><div><Label>Cloisons réparties</Label><Input inputMode="decimal" value={value.partitionLoad ?? "1.00"} onChange={event => update({ partitionLoad: event.target.value })} /></div><div><Label>Équipements fixes</Label><Input inputMode="decimal" value={value.equipmentLoad ?? "0.50"} onChange={event => update({ equipmentLoad: event.target.value })} /></div><div><Label>Exploitation</Label><Input inputMode="decimal" value={value.imposedLoad ?? "2.00"} onChange={event => update({ imposedLoad: event.target.value })} /></div><div><Label>Toiture / entretien</Label><Input inputMode="decimal" value={value.roofLoad ?? "0.80"} onChange={event => update({ roofLoad: event.target.value })} /></div></div><p className="mt-2 text-[9px] text-[#718083]">Valeurs à confirmer selon l’usage, les murs réellement portés et le référentiel national.</p></div>
      {errors.length > 0 && <div className="rounded-lg bg-[#fff0f0] p-3 text-[10px] text-[#b42318]">{errors.map(error => <div key={error}>{error}</div>)}</div>}
      <div className="rounded-lg bg-[#fff5e8] p-3 text-[10px] text-[#8a5a21]">Paramètres de prédimensionnement : la vérification finale dépend de la portée, des charges, des appuis, de la norme et du calcul d’un ingénieur.</div>
      <Button disabled={errors.length > 0} className="w-full bg-[#27358f] text-white disabled:opacity-40" onClick={onClose}>Enregistrer le plancher</Button>
    </CardContent></Card>
  </div>;
}
